### ISSUE TITLE
Enchanted backpack placement crash

### ISSUE THREAD

**Issue by Drumheld** [copygirl/WearableBackpacks#110]
I enchanted a wearable backpack with Protection IV and then placed it. as soon as the backpack enters the visual screen space of any player, the server kicks that player.

```
[20:28:01] [Netty Server IO #1/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: An existing connection was forcibly closed by the remote host
        at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[?:1.8.0_201]
        at sun.nio.ch.SocketDispatcher.read(Unknown Source) ~[?:1.8.0_201]
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source) ~[?:1.8.0_201]
        at sun.nio.ch.IOUtil.read(Unknown Source) ~[?:1.8.0_201]
        at sun.nio.ch.SocketChannelImpl.read(Unknown Source) ~[?:1.8.0_201]
        at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288) ~[PooledUnsafeDirectByteBuf.class:?]
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1100) ~[AbstractByteBuf.class:?]
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:372) ~[NioSocketChannel.class:?]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123) [AbstractNioByteChannel$NioByteUnsafe.class:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:624) [NioEventLoop.class:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [NioEventLoop.class:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) [NioEventLoop.class:?]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) [NioEventLoop.class:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [SingleThreadEventExecutor$5.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
```

**Comment by copygirl** [comment]
`An existing connection was forcibly closed by the remote host` from what I know is just a generic exception that occurs when a connection abruptly closes. Can you check for an exception that occurs around the same time? Both client and server. Is it reproducible? Does it really only happen with enchanted backpacks?

**Comment by Drumheld** [comment]
I will have to check back to the first instance of the crash, but I don't have that log at the moment. It is reproducible, as I had to roll back the world save to recover the lost items in our (thankfully) only other placed backpack with items inside, and the same issue occurred 

I resolved the issue with the initial world save by removing all backpack mods (server and client) and restoring them after a FML confirm and destroying the now defunct in-game backpack instances. I replaced the mod back into the mod-list and backpacks were again craft-able/wearable. 

The enchanted backpacks are the only thing that has caused this problem. I enchanted the backpack with Protection IV, held it in my hand, and placed it on the ground. The moment I placed it (and thereafter, whenever anybody entered the chunk facing the direction of the backpack) the client would crash and the server would eject them with the above message. 

I removed the shaders preset to ensure it wasn't some kind of local enchantment glisten phenomenon having to do with a light source.

**Comment by InsomniaKitten** [comment]
Please provide a mod list

**Comment by copygirl** [comment]
> [...] the client would crash and the server would eject them with the above message.

The client crash log would also be very helpful here. I hope you understand that without this information there's nothing we can to fix this bug.

**Comment by copygirl** [comment]
Will reopen when we have a full client (?) crash report we can use.
