### ISSUE TITLE
Shift-breaking a backpack while wearing one crashes the client.

### ISSUE THREAD

**Issue by maksymsen** [copygirl/WearableBackpacks#122]
**Versions:**

Minecraft: _1.12.2_
Wearable Backpacks: _3.1.4_
Forge: _14.23.5.2838_
Modpack: _RLCraft v2.7.1_

**Description:**

A little difficult to replicate and doesn't always work, but users have reported that shift-breaking a backpack whilst wearing one will crash the client. I reproduced this one earlier: While wearing a backpack, I started normally breaking a second backpack and shifted as soon as I saw the error popup that told me I was already wearing a backpack.

Not a critical bug as it is a niche case and often due to unfortunate timing, but it does exist.

Here's the exception:
```

java.lang.ArrayIndexOutOfBoundsException: -10
	at net.minecraft.client.renderer.RenderGlobal.func_174981_a(RenderGlobal.java:2786)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1844)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1613)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1384)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

[crash-2019-10-07_14.14.30-client.txt](https://github.com/copygirl/WearableBackpacks/files/3698901/crash-2019-10-07_14.14.30-client.txt)

**Comment by copygirl** [comment]
Closing in favor of #135, which has info on how to reproduce this crash, and cuts it down to it being an interaction between WBs and Multi Mine.
