### ISSUE TITLE
Why does my minecraft keep crashing With Wearable Backpacks? Forge 1.12.2... someone take a look?

### ISSUE THREAD

**Issue by jaymasone** [copygirl/WearableBackpacks#132]

**Comment by jaymasone** [comment]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  CharmLoadingPlugin (Charm-Mod-1.12.2.jar)
  CorePlugin (ForgeEndertech-1.12.2-4.5.2.0-build.0459.jar)
Contact their authors BEFORE contacting forge

// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 4/21/20 11:27 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Wearable Backpacks (wearablebackpacks)
Caused by: java.lang.IllegalArgumentException: Not within valid bounds [0,32000]
	at net.mcft.copy.backpacks.config.SettingInteger.parse(SettingInteger.java:31)
	at net.mcft.copy.backpacks.config.SettingInteger.parse(SettingInteger.java:8)
	at net.mcft.copy.backpacks.config.SettingSingleValue.loadFromConfiguration(SettingSingleValue.java:15)
	at net.mcft.copy.backpacks.config.BackpacksConfig.lambda$load$2(BackpacksConfig.java:190)
	at net.mcft.copy.backpacks.config.BackpacksConfig$$Lambda$488/371722788.accept(Unknown Source)
	at java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:600)
	at net.mcft.copy.backpacks.config.BackpacksConfig.load(BackpacksConfig.java:190)
	at net.mcft.copy.backpacks.WearableBackpacks.preInit(WearableBackpacks.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 324150904 bytes (309 MB) / 805306368 bytes (768 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 31 mods loaded, 31 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                  | Version           | Source                                       | Signature                                |
	|:----- |:------------------- |:----------------- |:-------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft           | 1.12.2            | minecraft.jar                                | None                                     |
	| LCH   | mcp                 | 9.42              | minecraft.jar                                | None                                     |
	| LCH   | FML                 | 8.0.99.99         | forge-1.12.2-14.23.5.2847.jar                | None                                     |
	| LCH   | forge               | 14.23.5.2847      | forge-1.12.2-14.23.5.2847.jar                | None                                     |
	| LCH   | forgeendertech      | 1.12.2-4.5.2.0    | ForgeEndertech-1.12.2-4.5.2.0-build.0459.jar | None                                     |
	| LCH   | adlods              | 1.12.2-1.0.7.1    | AdLods-1.12.2-1.0.7.1-build.0441.jar         | None                                     |
	| LCH   | baubles             | 1.5.2             | Baubles-Mod-1.12.2.jar                       | None                                     |
	| LCH   | bdlib               | 1.14.3.12         | bdlib-1.14.3.12-mc1.12.2 (1).jar             | None                                     |
	| LCH   | patchouli           | 1.0-20            | Patchouli-1.0-20.jar                         | None                                     |
	| LCH   | llibrary            | 1.7.18            | LLibrary-1.12.2.jar                          | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCH   | bewitchment         | @VERSION@         | Bewitchment-Mod-1.12.2.jar                   | None                                     |
	| LCH   | blockarmor          | 2.4.11            | BlockArmor-1.12.2-2.4.11.jar                 | None                                     |
	| LCH   | buildinggadgets     | 2.7.1             | BuildingGadgets-2.7.1 (1).jar                | None                                     |
	| LCH   | jei                 | 4.15.0.291        | jei_1.12.2-4.15.0.291.jar                    | None                                     |
	| LCH   | charm               | 1.12.2-1.3.6      | Charm-Mod-1.12.2.jar                         | None                                     |
	| LCH   | crafttweaker        | 4.1.20            | CraftTweaker2-1.12-4.1.20.564.jar            | None                                     |
	| LCH   | ctgui               | 1.0.0             | CraftTweaker2-1.12-4.1.20.564.jar            | None                                     |
	| LCH   | crafttweakerjei     | 2.0.3             | CraftTweaker2-1.12-4.1.20.564.jar            | None                                     |
	| LCH   | customnpcs          | 1.12              | CustomNPCs_1.12.2-(01Oct19).jar              | None                                     |
	| LCH   | cyclopscore         | 1.6.2             | CyclopsCore-1.12.2.jar                       | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| LCH   | cfm                 | 6.3.1             | furniture-6.3.1-1.12.2.jar                   | None                                     |
	| LCH   | ironchest           | 1.12.2-7.0.67.844 | ironchest-1.12.2-7.0.72.847.jar              | None                                     |
	| LCH   | mantle              | 1.12-1.3.3.55     | Mantle-1.12-1.3.3.55.jar                     | None                                     |
	| LCH   | mekanism            | 1.12.2-9.8.3.390  | Mekanism-1.12.2-9.8.3.390.jar                | None                                     |
	| LCH   | projecte            | 1.12.2-PE1.4.1    | ProjectE-1.12.2-PE1.4.1 (1).jar              | None                                     |
	| LCH   | tconstruct          | 1.12.2-2.13.0.183 | TConstruct-1.12.2-2.13.0.183.jar             | None                                     |
	| LCH   | xreliquary          | 1.12.2-1.3.4.796  | Reliquary-Mod-1.12.2.jar                     | None                                     |
	| LCH   | veinminer           | 0.38.2            | VeinMiner-1.12-0.38.2.647+b31535a.jar        | None                                     |
	| LCH   | veinminermodsupport | 0.38.2            | VeinMiner-1.12-0.38.2.647+b31535a.jar        | None                                     |
	| LCE   | wearablebackpacks   | 3.1.3             | Wearable-Backpacks-Mod-1.12.2.jar            | None                                     |
	| LC    | xray                | 2.0.0             | xray-1.12.2-1.6.0.jar                        | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  mekanism.coremod.KeybindingMigrationHelper
CharmLoadingPlugin (Charm-Mod-1.12.2.jar)
  svenhjol.charm.base.CharmClassTransformer
CorePlugin (ForgeEndertech-1.12.2-4.5.2.0-build.0459.jar)
  
	GL info: ' Vendor: 'Intel' Version: '4.5.0 - Build 22.20.16.4749' Renderer: 'Intel(R) HD Graphics 520'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

	List of loaded APIs: 
		* Baubles|API (1.4.0.2) from Baubles-Mod-1.12.2.jar
		* BewitchmentAPI (0.0.19.5) from Bewitchment-Mod-1.12.2.jar
		* Core (0.1) from CustomNPCs_1.12.2-(01Oct19).jar
		* Core|Blocks (0.1) from CustomNPCs_1.12.2-(01Oct19).jar
		* Core|Constants (0.1) from CustomNPCs_1.12.2-(01Oct19).jar
		* Core|Entities (0.1) from CustomNPCs_1.12.2-(01Oct19).jar
		* Core|Entities|Data (0.1) from CustomNPCs_1.12.2-(01Oct19).jar
		* Core|Entities|Data|Role (0.1) from CustomNPCs_1.12.2-(01Oct19).jar
		* Core|Events (0.1) from CustomNPCs_1.12.2-(01Oct19).jar
		* Core|Handlers (0.1) from CustomNPCs_1.12.2-(01Oct19).jar
		* Core|Handlers|Data (0.1) from CustomNPCs_1.12.2-(01Oct19).jar
		* ForgeEndertechAPI (1.0) from ForgeEndertech-1.12.2-4.5.2.0-build.0459.jar
		* JustEnoughItemsAPI (4.13.0) from jei_1.12.2-4.15.0.291.jar
		* MekanismAPI|core (9.8.1) from Mekanism-1.12.2-9.8.3.390.jar
		* MekanismAPI|energy (9.8.1) from Mekanism-1.12.2-9.8.3.390.jar
		* MekanismAPI|gas (9.8.1) from Mekanism-1.12.2-9.8.3.390.jar
		* MekanismAPI|infuse (9.8.1) from Mekanism-1.12.2-9.8.3.390.jar
		* MekanismAPI|laser (9.8.1) from Mekanism-1.12.2-9.8.3.390.jar

**Comment by jaymasone** [comment]
> ---- Minecraft Crash Report ----
> WARNING: coremods are present:
> llibrary (llibrary-core-1.0.11-1.12.2.jar)
> MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
> CharmLoadingPlugin (Charm-Mod-1.12.2.jar)
> CorePlugin (ForgeEndertech-1.12.2-4.5.2.0-build.0459.jar)
> Contact their authors BEFORE contacting forge
> // Hi. I'm Minecraft, and I'm a crashaholic.
> Time: 4/21/20 11:27 PM
> Description: There was a severe problem during mod loading that has caused the game to fail
> net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Wearable Backpacks (wearablebackpacks)
> Caused by: java.lang.IllegalArgumentException: Not within valid bounds [0,32000]
> at net.mcft.copy.backpacks.config.SettingInteger.parse(SettingInteger.java:31)
> at net.mcft.copy.backpacks.config.SettingInteger.parse(SettingInteger.java:8)
> at net.mcft.copy.backpacks.config.SettingSingleValue.loadFromConfiguration(SettingSingleValue.java:15)
> at net.mcft.copy.backpacks.config.BackpacksConfig.lambda$load$2(BackpacksConfig.java:190)
> at net.mcft.copy.backpacks.config.BackpacksConfig$$Lambda$488/371722788.accept(Unknown Source)
> at java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:600)
> at net.mcft.copy.backpacks.config.BackpacksConfig.load(BackpacksConfig.java:190)
> at net.mcft.copy.backpacks.WearableBackpacks.preInit(WearableBackpacks.java:44)
> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> at java.lang.reflect.Method.invoke(Method.java:497)
> at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
> at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> at java.lang.reflect.Method.invoke(Method.java:497)
> at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
> at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
> at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
> at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
> at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
> at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
> at com.google.common.eventbus.EventBus.post(EventBus.java:217)
> at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
> at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> at java.lang.reflect.Method.invoke(Method.java:497)
> at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
> at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
> at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
> at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
> at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
> at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
> at com.google.common.eventbus.EventBus.post(EventBus.java:217)
> at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
> at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
> at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
> at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
> at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
> at net.minecraft.client.main.Main.main(SourceFile:123)
> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> at java.lang.reflect.Method.invoke(Method.java:497)
> at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
> at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
> A detailed walkthrough of the error, its code path and all known details is as follows:
> -- System Details --
> Details:
> Minecraft Version: 1.12.2
> Operating System: Windows 10 (amd64) version 10.0
> Java Version: 1.8.0_51, Oracle Corporation
> Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
> Memory: 324150904 bytes (309 MB) / 805306368 bytes (768 MB) up to 2147483648 bytes (2048 MB)
> JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
> IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
> FML: MCP 9.42 Powered by Forge 14.23.5.2847 31 mods loaded, 31 mods active
> States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
> | State | ID                  | Version           | Source                                       | Signature                                |
> |:----- |:------------------- |:----------------- |:-------------------------------------------- |:---------------------------------------- |
> | LCH   | minecraft           | 1.12.2            | minecraft.jar                                | None                                     |
> | LCH   | mcp                 | 9.42              | minecraft.jar                                | None                                     |
> | LCH   | FML                 | 8.0.99.99         | forge-1.12.2-14.23.5.2847.jar                | None                                     |
> | LCH   | forge               | 14.23.5.2847      | forge-1.12.2-14.23.5.2847.jar                | None                                     |
> | LCH   | forgeendertech      | 1.12.2-4.5.2.0    | ForgeEndertech-1.12.2-4.5.2.0-build.0459.jar | None                                     |
> | LCH   | adlods              | 1.12.2-1.0.7.1    | AdLods-1.12.2-1.0.7.1-build.0441.jar         | None                                     |
> | LCH   | baubles             | 1.5.2             | Baubles-Mod-1.12.2.jar                       | None                                     |
> | LCH   | bdlib               | 1.14.3.12         | bdlib-1.14.3.12-mc1.12.2 (1).jar             | None                                     |
> | LCH   | patchouli           | 1.0-20            | Patchouli-1.0-20.jar                         | None                                     |
> | LCH   | llibrary            | 1.7.18            | LLibrary-1.12.2.jar                          | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
> | LCH   | bewitchment         | @VERSION@         | Bewitchment-Mod-1.12.2.jar                   | None                                     |
> | LCH   | blockarmor          | 2.4.11            | BlockArmor-1.12.2-2.4.11.jar                 | None                                     |
> | LCH   | buildinggadgets     | 2.7.1             | BuildingGadgets-2.7.1 (1).jar                | None                                     |
> | LCH   | jei                 | 4.15.0.291        | jei_1.12.2-4.15.0.291.jar                    | None                                     |
> | LCH   | charm               | 1.12.2-1.3.6      | Charm-Mod-1.12.2.jar                         | None                                     |
> | LCH   | crafttweaker        | 4.1.20            | CraftTweaker2-1.12-4.1.20.564.jar            | None                                     |
> | LCH   | ctgui               | 1.0.0             | CraftTweaker2-1.12-4.1.20.564.jar            | None                                     |
> | LCH   | crafttweakerjei     | 2.0.3             | CraftTweaker2-1.12-4.1.20.564.jar            | None                                     |
> | LCH   | customnpcs          | 1.12              | CustomNPCs_1.12.2-(01Oct19).jar              | None                                     |
> | LCH   | cyclopscore         | 1.6.2             | CyclopsCore-1.12.2.jar                       | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
> | LCH   | cfm                 | 6.3.1             | furniture-6.3.1-1.12.2.jar                   | None                                     |
> | LCH   | ironchest           | 1.12.2-7.0.67.844 | ironchest-1.12.2-7.0.72.847.jar              | None                                     |
> | LCH   | mantle              | 1.12-1.3.3.55     | Mantle-1.12-1.3.3.55.jar                     | None                                     |
> | LCH   | mekanism            | 1.12.2-9.8.3.390  | Mekanism-1.12.2-9.8.3.390.jar                | None                                     |
> | LCH   | projecte            | 1.12.2-PE1.4.1    | ProjectE-1.12.2-PE1.4.1 (1).jar              | None                                     |
> | LCH   | tconstruct          | 1.12.2-2.13.0.183 | TConstruct-1.12.2-2.13.0.183.jar             | None                                     |
> | LCH   | xreliquary          | 1.12.2-1.3.4.796  | Reliquary-Mod-1.12.2.jar                     | None                                     |
> | LCH   | veinminer           | 0.38.2            | VeinMiner-1.12-0.38.2.647+b31535a.jar        | None                                     |
> | LCH   | veinminermodsupport | 0.38.2            | VeinMiner-1.12-0.38.2.647+b31535a.jar        | None                                     |
> | LCE   | wearablebackpacks   | 3.1.3             | Wearable-Backpacks-Mod-1.12.2.jar            | None                                     |
> | LC    | xray                | 2.0.0             | xray-1.12.2-1.6.0.jar                        | None                                     |
> 
> Loaded coremods (and transformers): 
> 
> llibrary (llibrary-core-1.0.11-1.12.2.jar)
> net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
> net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
> MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
> mekanism.coremod.KeybindingMigrationHelper
> CharmLoadingPlugin (Charm-Mod-1.12.2.jar)
> svenhjol.charm.base.CharmClassTransformer
> CorePlugin (ForgeEndertech-1.12.2-4.5.2.0-build.0459.jar)
> GL info: ' Vendor: 'Intel' Version: '4.5.0 - Build 22.20.16.4749' Renderer: 'Intel(R) HD Graphics 520'
> Pulsar/tconstruct loaded Pulses: 
> 	- TinkerCommons (Enabled/Forced)
> 	- TinkerWorld (Enabled/Not Forced)
> 	- TinkerTools (Enabled/Not Forced)
> 	- TinkerHarvestTools (Enabled/Forced)
> 	- TinkerMeleeWeapons (Enabled/Forced)
> 	- TinkerRangedWeapons (Enabled/Forced)
> 	- TinkerModifiers (Enabled/Forced)
> 	- TinkerSmeltery (Enabled/Not Forced)
> 	- TinkerGadgets (Enabled/Not Forced)
> 	- TinkerOredict (Enabled/Forced)
> 	- TinkerIntegration (Enabled/Forced)
> 	- TinkerFluids (Enabled/Forced)
> 	- TinkerMaterials (Enabled/Forced)
> 	- TinkerModelRegister (Enabled/Forced)
> 
> List of loaded APIs: 
> 	* Baubles|API (1.4.0.2) from Baubles-Mod-1.12.2.jar
> 	* BewitchmentAPI (0.0.19.5) from Bewitchment-Mod-1.12.2.jar
> 	* Core (0.1) from CustomNPCs_1.12.2-(01Oct19).jar
> 	* Core|Blocks (0.1) from CustomNPCs_1.12.2-(01Oct19).jar
> 	* Core|Constants (0.1) from CustomNPCs_1.12.2-(01Oct19).jar
> 	* Core|Entities (0.1) from CustomNPCs_1.12.2-(01Oct19).jar
> 	* Core|Entities|Data (0.1) from CustomNPCs_1.12.2-(01Oct19).jar
> 	* Core|Entities|Data|Role (0.1) from CustomNPCs_1.12.2-(01Oct19).jar
> 	* Core|Events (0.1) from CustomNPCs_1.12.2-(01Oct19).jar
> 	* Core|Handlers (0.1) from CustomNPCs_1.12.2-(01Oct19).jar
> 	* Core|Handlers|Data (0.1) from CustomNPCs_1.12.2-(01Oct19).jar
> 	* ForgeEndertechAPI (1.0) from ForgeEndertech-1.12.2-4.5.2.0-build.0459.jar
> 	* JustEnoughItemsAPI (4.13.0) from jei_1.12.2-4.15.0.291.jar
> 	* MekanismAPI|core (9.8.1) from Mekanism-1.12.2-9.8.3.390.jar
> 	* MekanismAPI|energy (9.8.1) from Mekanism-1.12.2-9.8.3.390.jar
> 	* MekanismAPI|gas (9.8.1) from Mekanism-1.12.2-9.8.3.390.jar
> 	* MekanismAPI|infuse (9.8.1) from Mekanism-1.12.2-9.8.3.390.jar
> 	* MekanismAPI|laser (9.8.1) from Mekanism-1.12.2-9.8.3.390.jar
