### ISSUE TITLE
soft ban caused near death

### ISSUE THREAD

**Issue by boringboredom0** [copygirl/WearableBackpacks#150]
I was playing on a custom modpack when I died from fall damage, i went to go pick up my items and while i was picking up items i got kicked. I assume i picked up the backpack item and it freaked out. It would then not let me connect to the server each time saying "internal server error"

i got this for the stacktrace on the server

Caused by: java.lang.UnsupportedOperationException
        at java.util.AbstractList.add(AbstractList.java:153) ~[?:?]
        at net.minecraft.class_2371.add(class_2371.java:61) ~[minecraft-1.19.2.i0:0/:?]
        at java.util.AbstractList.add(AbstractList.java:111) ~[?:?]
        at dev.sapphic.wearablebackpacks.Backpack.getContents(Backpack.java:95) ~[wearablebackpacks-4.1.1.i0:0/:?]
        at dev.sapphic.wearablebackpacks.item.BackpackItem.method_7888(BackpackItem.java:117) ~[wearablebackpacks-4.1.1.i0:0/:?]
        at net.minecraft.class_1799.method_7917(class_1799.java:542) ~[minecraft-1.19.2.i0:0/:?]
        at net.minecraft.class_1661.method_7381(class_1661.java:255) ~[minecraft-1.19.2.i0:0/:?]
        at net.minecraft.class_1657.method_6007(class_1657.java:567) ~[minecraft-1.19.2.i0:0/:?]
        at net.minecraft.class_1309.method_5773(class_1309.java:2385) ~[minecraft-1.19.2.i0:0/:?]
        at net.minecraft.class_1657.method_5773(class_1657.java:284) ~[minecraft-1.19.2.i0:0/:?]
        at net.minecraft.class_3222.method_14226(class_3222.java:487) ~[minecraft-1.19.2.i0:0/:?]

then a few times after trying to join i got this stacktrace which is different

[23:27:06] [Netty Server IO #6/ERROR]: Exception occurred in netty pipeline
io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(19) + length(1) exceeds writerIndex(19): PooledSlicedByteBuf(ridx: 19, widx: 19, cap: 19/19, unwrapped: PooledUnsafeDirectByteBuf(ridx: 20, widx: 20, cap: 2048))
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:480) ~[minecraft-1.19.2.i0:0/:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279) ~[minecraft-1.19.2.i0:0/:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [minecraft-1.19.2.i0:0/:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [minecraft-1.19.2.i0:0/:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [minecraft-1.19.2.i0:0/:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) [minecraft-1.19.2.i0:0/:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299) [minecraft-1.19.2.i0:0/:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [minecraft-1.19.2.i0:0/:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [minecraft-1.19.2.i0:0/:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [minecraft-1.19.2.i0:0/:?]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [minecraft-1.19.2.i0:0/:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [minecraft-1.19.2.i0:0/:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [minecraft-1.19.2.i0:0/:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [minecraft-1.19.2.i0:0/:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [minecraft-1.19.2.i0:0/:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [minecraft-1.19.2.i0:0/:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [minecraft-1.19.2.i0:0/:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [minecraft-1.19.2.i0:0/:?]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) [minecraft-1.19.2.i0:0/:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722) [minecraft-1.19.2.i0:0/:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658) [minecraft-1.19.2.i0:0/:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584) [minecraft-1.19.2.i0:0/:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) [minecraft-1.19.2.i0:0/:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) [minecraft-1.19.2.i0:0/:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [minecraft-1.19.2.i0:0/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(19) + length(1) exceeds writerIndex(19): PooledSlicedByteBuf(ridx: 19, widx: 19, cap: 19/19, unwrapped: PooledUnsafeDirectByteBuf(ridx: 20, widx: 20, cap: 2048))
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442) ~[minecraft-1.19.2.i0:0/:?]
	at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:730) ~[minecraft-1.19.2.i0:0/:?]
	at io.netty.buffer.AbstractByteBuf.readBoolean(AbstractByteBuf.java:739) ~[minecraft-1.19.2.i0:0/:?]
	at net.minecraft.class_2540.readBoolean(class_2540.java:1187) ~[minecraft-1.19.2.i0:0/:?]
	at net.minecraft.class_2540.method_37436(class_2540.java:241) ~[minecraft-1.19.2.i0:0/:?]
	at net.minecraft.class_2915.<init>(class_2915.java:13) ~[minecraft-1.19.2.i0:0/:?]
	at net.minecraft.class_2539$class_4532.method_22310(class_2539.java:433) ~[minecraft-1.19.2.i0:0/:?]
	at net.minecraft.class_2539.method_10783(class_2539.java:485) ~[minecraft-1.19.2.i0:0/:?]
	at net.minecraft.class_2543.decode(class_2543.java:32) ~[minecraft-1.19.2.i0:0/:?]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510) ~[minecraft-1.19.2.i0:0/:?]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449) ~[minecraft-1.19.2.i0:0/:?]
	... 25 more

**Comment by boringboredom0** [comment]
wait sorry apparently im using a different version of this mod updated for 1.19.2 and the developer of the version did not change the issues link somewhere and lead me to here
