### ISSUE TITLE
Crash with ver. 2.2.0 at Forge 13.20.0.2222

### ISSUE THREAD

**Issue by Baalith** [copygirl/WearableBackpacks#4]
Here's my crashlog:

// Why is it breaking :(

Time: 2/3/17 7:39 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Wearable Backpacks (wearablebackpacks)
Caused by: java.lang.NoSuchMethodError: net.mcft.copy.backpacks.item.ItemBackpack.setUnlocalizedName(Ljava/lang/String;)Lnet/minecraft/item/Item;
	at net.mcft.copy.backpacks.item.ItemBackpack.<init>(ItemBackpack.java:48)
	at net.mcft.copy.backpacks.BackpacksContent.init(BackpacksContent.java:26)
	at net.mcft.copy.backpacks.WearableBackpacks.preInit(WearableBackpacks.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:641)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:246)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:224)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:147)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:628)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:268)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:440)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:352)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 50005728 bytes (47 MB) / 420478976 bytes (401 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2048M -XX:+UseG1GC -XX:+DisableExplicitGC -XX:MaxGCPauseMillis=10 -XX:SoftRefLRUPolicyMSPerMB=10000 -XX:ParallelGCThreads=7 -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.38 Powered by Forge 13.20.0.2222 Optifine OptiFine_1.11.2_HD_U_B6 45 mods loaded, 45 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2222.jar) 
	UCH	forge{13.20.0.2222} [Minecraft Forge] (forge-1.11.2-13.20.0.2222.jar) 
	UCH	bspkrscore{7.5.2} [bspkrsCore] ([1.11.2]bspkrsCore-universal-7.5.2.jar) 
	UCH	treecapitator{1.42} [TreeCapitator] ([1.11.2]TreeCapitator-client-1.42.jar) 
	UCH	forgeendertech{2.0.2.0} [Forge Endertech] (ForgeEndertech-1.11.2-2.0.2.0.jar) 
	UCH	adchimneys{1.11.2-2.0.2.0} [Advanced Chimneys] (AdChimneys-1.11.2-2.0.2.0.jar) 
	UCH	betterachievements{0.4.1.44} [Better Achievements] (BetterAchievements-1.11.2-0.4.1.44.jar) 
	UCH	betterfoliage{2.1.3} [Better Foliage] (BetterFoliage-MC1.11.2-2.1.3.jar) 
	UCH	biomesoplenty{6.0.1.2145} [Biomes O' Plenty] (BiomesOPlenty-1.11.2-6.0.1.2145-universal.jar) 
	UCH	ceanimals{1.3.0} [Crop-Eating Animals] (ceanimals-1.11.2-1.3.0.jar) 
	UCH	cfm{4.1.2} [MrCrayfish's Furniture Mod] (cfm-4.1.2-mc1.11.2.jar) 
	UCH	chameleon{1.11-3.0.2} [Chameleon] (Chameleon-1.11-3.0.2.jar) 
	UCH	chiselsandbits{13.9} [Chisels & Bits] (chiselsandbits-13.9.jar) 
	UCH	clockhud{1.3.3} [Clock HUD] (ClockHUD-1.11-1.3.3.jar) 
	UCH	dsurround{3.2.5.0} [Dynamic Surroundings] (DynamicSurroundings-1.11.2-3.2.5.0.jar) 
	UCH	endercompass{1.2.5.1} [Ender Compass] (EnderCompass-1.11-1.2.5.1.jar) 
	UCH	extrabitmanipulation{1.11.2-3.0.4} [Extra Bit Manipulation] (ExtraBitManipulation-1.11.2-3.0.4.jar) 
	UCH	globalgamerules{2.0} [Global GameRules] (GlobalGameRules-1.11-2.0.jar) 
	UCH	gravestone{1.7.2} [Gravestone] (GraveStone Mod 1.7.2.jar) 
	UCH	waila{1.8.9} [Waila] (Hwyla-1.8.9-B22_1.11.jar) 
	UCH	inventorytweaks{1.62-dev-76-4165ce4} [Inventory Tweaks] (InventoryTweaks-1.62-dev-76.jar) 
	UCH	jei{4.2.4.226} [Just Enough Items] (jei_1.11.2-4.2.4.226.jar) 
	UCH	levels{r1.0.0} [Levels] (Levels 2-1.11.2-r1.0.0.jar) 
	UCH	levelup{${version}} [Level Up!] (LevelUp!-0.13.2-1.11.jar) 
	UCH	shadowmc{3.7.1} [ShadowMC] (ShadowMC-1.11-3.7.4.jar) 
	UCH	leveluphp{1.0.1} [Level Up HP] (leveluphp-1.11-1.0.1.jar) 
	UCH	mapwriter{2.7.0} [MapWriter] (MapWriter-1.11.2-2.7.0.jar) 
	UCH	minecolonies{1.11-0.6.2604} [MineColonies] (minecolonies-universal-1.11-0.6.2604.jar) 
	UCH	naturescompass{1.3.0} [Nature's Compass] (NaturesCompass-1.11.2-1.3.0.jar) 
	UCH	placeableitems{3.0.3.1} [Placeable Items Mod] (placeableitems-3.0.3.1.jar) 
	UCH	guilib{1.11 : updated by subaraki} [GUI Library] (PSG Revamper-1.11-1.0.0.0.jar) 
	UCH	paintingselgui{1.11 v1: updated by Subaraki} [PaintingSelectionGui] (PSG Revamper-1.11-1.0.0.0.jar) 
	UCH	roguelike{1.6.3} [Roguelike Dungeons] (RoguelikeDungeons-1.11.2-1.6.3.jar) 
	UCH	ruins{16.4} [Ruins Mod] (Ruins-1.11.2.jar) 
	UCH	scenter{1.11.2-3.10.1} [Scenter] (scenter-1.11.2-3.10.1.jar) 
	UCH	soundfilters{0.9_for_1.9} [Sound Filters] (SoundFilters-0.9_for_1.11.jar) 
	UCH	storagedrawers{1.11.2-4.1.0} [Storage Drawers] (StorageDrawers-1.11.2-4.1.0.jar) 
	UCH	thutcore{4.3.2} [ThutCore] (thutcore-4.3.2.jar) 
	UCH	thuttech{5.0.0} [Thut's Tech] (thuttech-5.0.0.jar) 
	UCH	undergroundbiomes{0.9.beta.8} [Underground Biomes] (UndergroundBiomesConstructs-1.11-0.9-beta.13.jar) 
	UCH	wailaharvestability{1.1.9} [Waila Harvestability] (WailaHarvestability-mc1.11-1.1.9.jar) 
	UCH	waystones{3.0.9} [Waystones] (Waystones_1.11.2-3.0.9.jar) 
	UCE	wearablebackpacks{2.2.0} [Wearable Backpacks] (WearableBackpacks-1.11.2-2.2.0.jar) 
	Loaded coremods (and transformers): 
ForgelinPlugin (Forgelin-1.2.0.jar)
  
DynamicSurroundingsCore (DynamicSurroundings-1.11.2-3.2.5.0.jar)
  org.blockartistry.mod.DynSurround.asm.Transformer
FMLPlugin (InventoryTweaks-1.62-dev-76.jar)
  invtweaks.forge.asm.ContainerTransformer
BetterFoliageLoader (BetterFoliage-MC1.11.2-2.1.3.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '3.3.11672 Compatibility Profile Context' Renderer: 'ATI Radeon HD 4800 Series'

Hope this helps to track down the issue.
BTW: ver. 2.1.0 worked like a charm :)

**Comment by copygirl** [comment]
Thanks for letting me know! I must have somehow compiled without the workspace set up properly or something? I reuploaded the proper, fixed 2.2.0.
