### ISSUE TITLE
Crash when chisel mod Installing

### ISSUE THREAD

**Issue by Senyum** [copygirl/WearableBackpacks#83]
Hi, i get bug in your cool mod. Its crashing game when i want to break backpack and get it on back. Here Crash report.
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 2018-07-08 20:05:16 MSK
Description: Playing level event

java.lang.IllegalArgumentException: Cannot set property PropertyAnyInteger{name=variation, clazz=class java.lang.Integer, values=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]} to 16 on block chisel:valentines, it is not an allowed value
    at net.minecraft.block.state.BlockStateContainer$StateImplementation.withProperty(BlockStateContainer.java:235)
    at team.chisel.common.block.BlockCarvable.getStateFromMeta(BlockCarvable.java:109)
    at net.minecraft.client.renderer.RenderGlobal.playEvent(RenderGlobal.java:3398)
    at net.minecraft.world.World.playEvent(World.java:3700)
    at net.minecraft.world.World.playEvent(World.java:3691)
    at net.minecraft.client.multiplayer.PlayerControllerMP.onPlayerDestroyBlock(PlayerControllerMP.java:155)
    at net.minecraft.client.multiplayer.PlayerControllerMP.onPlayerDamageBlock(PlayerControllerMP.java:322)
    at PlayerControllerOF.onPlayerDamageBlock(PlayerControllerOF.java:65)
    at net.minecraft.client.Minecraft.sendClickBlockToController(Minecraft.java:1478)
    at net.minecraft.client.Minecraft.processKeyBinds(Minecraft.java:2266)
    at net.minecraft.client.Minecraft.runTickKeyboard(Minecraft.java:2018)
    at net.minecraft.client.Minecraft.runTick(Minecraft.java:1806)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1096)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3937)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Senyum** [comment]
Yes, VanillaFix installed with extended ID addon

**Comment by asiekierka** [comment]
This is a JEIDs issue, not a WearableBackpacks issue.

**Comment by Senyum** [comment]
Thank you. When i delete Chisel its working.
